Update package.json
add missing optimist dep used for 

```
# node_modules/.bin/dbus2js
module.js:471
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:469:15)
```